### ISSUE TITLE
When is the launch from stable "enough" or out of preview?

### ISSUE THREAD

**Issue by voladelta** [wieslawsoltes/MinimalAvalonia#10]
Hi Wiesław Šoltés

Thank you for the project.

Do you have a plan for out-of-preview?

This is really cool project. Especially, for someone like me from web dev like Vue/React, and dont want to install heavy Visual Studio just for XAML.

I'm new but i'd like to contribute in the future. Do you have a roadmap?

**Comment by wieslawsoltes** [comment]
It follows the Avalonia versioning so if Avalonia release next stable (hopefully soon) I will release stable version.

Anyway I think it's pretty stable as Avalonia v11 preview3 is pretty solid.

Sorry don't have any roadmap, most of stuff from Avalonia is available, if you miss something please file and issue so we can see if it doable and how we can proceed.

**Comment by wieslawsoltes** [comment]
@voladelta Also there is another project fro Avalonia pretty similar you may like to explore: https://github.com/AvaloniaUI/Avalonia.Markup.Declarative

**Comment by voladelta** [comment]
Wow, thank you for your time and quick reply! Didn't expect that fast. 👍🤟
